[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.your-ai-assistant.com; img-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
